import { InlineKeyboard } from "grammy"

export function createTelegramSkillsMenu({ discoverSkills, createGeneratedSkill, reply, logger }) {
  const creationStates = new Map()

  return {
    async handleCommand(ctx) {
      if (telegramCommandArgs(ctx) === "create") {
        creationStates.set(pendingSkillKey(ctx), { step: "name" })
        await reply(ctx, "Skill name? Send a short name, or /cancel.")
        return
      }

      const result = await discoverSkills()
      logger?.debug?.(
        skillsDiscoveryLogContext(result),
        "OpenCode skills discovered for Telegram menu",
      )
      const keyboard = new InlineKeyboard()
        .text("Refresh", "skills:refresh")
        .row()
        .text("Create generated skill", "skills:create")
      await reply(ctx, formatSkillsList(result), { reply_markup: keyboard })
    },

    async handleCallback(ctx) {
      const action = ctx.match?.[1]
      if (action === "create") {
        creationStates.set(pendingSkillKey(ctx), { step: "name" })
        await ctx.answerCallbackQuery?.({ text: "Creating generated skill" })
        await reply(ctx, "Skill name? Send a short name, or /cancel.")
        return
      }
      if (action === "refresh") {
        await ctx.answerCallbackQuery?.({ text: "Refreshing skills" })
        await this.handleCommand(ctx)
      }
    },

    async handlePendingText(ctx) {
      const key = pendingSkillKey(ctx)
      const state = creationStates.get(key)
      if (!state) {
        return false
      }

      const text = String(ctx.message?.text ?? "").trim()
      if (text === "/cancel") {
        creationStates.delete(key)
        await reply(ctx, "Skill creation cancelled.")
        return true
      }

      if (state.step === "name") {
        creationStates.set(key, { ...state, step: "description", name: text })
        await reply(ctx, "Skill trigger description? Start with 'Use when ...', or /cancel.")
        return true
      }

      if (state.step === "description") {
        creationStates.set(key, { ...state, step: "body", description: text })
        await reply(ctx, "Skill instructions? Send the body text, or /cancel.")
        return true
      }

      if (state.step === "body") {
        creationStates.set(key, { ...state, step: "confirm", body: text })
        await reply(ctx, formatGeneratedSkillPreview({ ...state, body: text }))
        return true
      }

      if (state.step === "confirm") {
        if (!isAffirmative(text)) {
          creationStates.delete(key)
          await reply(ctx, "Skill creation cancelled.")
          return true
        }
        const created = await createGeneratedSkill({
          scope: "project",
          name: state.name,
          description: state.description,
          body: state.body,
          overwrite: false,
        })
        logger?.debug?.(
          { generatedSkillName: created.skillName, scope: created.scope ?? "project" },
          "OpenCode generated skill created from Telegram menu",
        )
        creationStates.delete(key)
        await reply(
          ctx,
          [
            `Created generated skill ${created.skillName}.`,
            `Path: ${created.filePath}`,
            "Restart OpenCode or start a fresh OpenCode process if the skill is not discovered immediately.",
          ].join("\n"),
        )
        return true
      }

      return false
    },
  }
}

function skillsDiscoveryLogContext({ skills = [], remoteSkillUrls = [] } = {}) {
  return {
    generatedSkillCount: skills.filter((skill) => skill.generated).length,
    remoteSkillUrlCount: remoteSkillUrls.length,
    skillCount: skills.length,
    skillScopes: uniqueSorted(skills.map((skill) => skill.scope)),
    skillSources: uniqueSorted(skills.map((skill) => skill.source)),
  }
}

function uniqueSorted(values) {
  return [...new Set(values.filter(Boolean))].sort()
}

function formatSkillsList({ skills = [], remoteSkillUrls = [] } = {}) {
  const projectSkills = skills.filter((skill) => skill.scope === "project" && !skill.generated)
  const generatedSkills = skills.filter((skill) => skill.generated)
  const externalSkills = skills.filter((skill) => skill.scope !== "project" && !skill.generated)
  const sections = ["OpenCode skills"]

  appendSkillSection(sections, "Project skills", projectSkills)
  appendSkillSection(sections, "Generated by OpenCode Remote", generatedSkills)
  appendSkillSection(sections, "External compatible skills", externalSkills)

  if (remoteSkillUrls.length > 0) {
    sections.push("", "Remote skill URLs are configured but not listed yet.")
  }
  if (sections.length === 1) {
    sections.push("", "No local OpenCode skills found.")
  }

  return sections.join("\n")
}

function appendSkillSection(sections, title, skills) {
  if (skills.length === 0) {
    return
  }
  sections.push("", title)
  for (const skill of skills) {
    sections.push(`${sectionsSkillCount(sections)}. ${skill.name} - ${skill.description}`)
  }
}

function sectionsSkillCount(sections) {
  return sections.filter((line) => /^\d+\. /u.test(line)).length + 1
}

function formatGeneratedSkillPreview({ name, description, body }) {
  return [
    "Create generated project skill?",
    "",
    `Name: ${name}`,
    `Description: ${description}`,
    "Destination: .opencode/skills/opencode-remote-generated/<skill-name>/SKILL.md",
    "",
    "Instructions:",
    body,
    "",
    "Reply yes to create it, or /cancel.",
  ].join("\n")
}

function isAffirmative(text) {
  return /^(yes|y)$/iu.test(String(text ?? "").trim())
}

function pendingSkillKey(ctx) {
  return String(ctx.chat?.id ?? ctx.message?.chat?.id ?? ctx.from?.id ?? "unknown")
}

function telegramCommandArgs(ctx) {
  const text = String(ctx.message?.text ?? "")
  return text.replace(/^\/skills(?:@\S+)?\s*/iu, "").trim()
}
